# Bar plot styles (used with ax.bar)
bar_styles = {
    "hash_linked_list": {
        "label": "Hash linked list",
        "color": "None",
        "edgecolor": "black",
        "hatch": "////",
    },
    "hash_linked_list_optimized": {
        "label": "Hash linked list optimized",
        "color": "None",
        "edgecolor": "black",
        "hatch": "////",
    },
    "hash_linked_list_optimized-X4-H100000": {
        "label": "Hash linked list optimized X4 H100k",
        "color": "None",
        "edgecolor": "black",
        "hatch": "////",
    },
    "hash_linked_list_X6_H100000": {
        "label": "Hash linked list X6 H100k",
        "color": "None",
        "edgecolor": "black",
        "hatch": "////",
    },
    "hash_skip_list": {
        "label": "Hash skip list",
        "color": "None",
        "edgecolor": "black",
        "hatch": "\\\\",
    },
    "hash_skip_list-X6-H100000": {
        "label": "Hash skip list X6 H100k",
        "color": "None",
        "edgecolor": "black",
        "hatch": "\\\\",
    },
    "skiplist": {
        "label": "Skip-list",
        "color": "None",
        "edgecolor": "black",
        "hatch": "++++",
    },
    "AlwayssortedVector": {
        "label": "Always-sorted vector",
        "color": "None",
        "edgecolor": "black",
        "hatch": "....",
    },
    "AlwayssortedVector-dynamic": {
        "label": "Always-sorted vector dynamic",
        "color": "None",
        "edgecolor": "black",
        "hatch": "....",
    },
    "AlwayssortedVector-preallocated": {
        "label": "Always-sorted vector prealloc",
        "color": "None",
        "edgecolor": "black",
        "hatch": "....",
    },
    "UnsortedVector": {
        "label": "Unsorted vector",
        "color": "None",
        "edgecolor": "black",
        "hatch": "xxxx",
    },
    "UnsortedVector-dynamic": {
        "label": "Unsorted vector dynamic",
        "color": "None",
        "edgecolor": "black",
        "hatch": "xxxx",
    },
    "UnsortedVector-preallocated": {
        "label": "Unsorted vector prealloc",
        "color": "None",
        "edgecolor": "black",
        "hatch": "xxxx",
    },
    "Vector": {
        "label": "Vector",
        "color": "None",
        "edgecolor": "black",
        "hatch": "----",
    },
    "Vector-dynamic": {
        "label": "Vector dynamic",
        "color": "None",
        "edgecolor": "black",
        "hatch": "----",
    },
    "Vector-preallocated": {
        "label": "Vector prealloc",
        "color": "None",
        "edgecolor": "black",
        "hatch": "----",
    },
    "hash_linked_list-X6-H100000": {
        "label": "Hash linked list X6 H100k",
        "color": "None",
        "edgecolor": "black",
        "hatch": "////",
    },
}

# Line plot styles (used with ax.plot)
line_styles = {
    "hash_linked_list": {
        "label": "Hash linked list",
        "color": "black",
        "linestyle": "--",
        "marker": "D",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "hash_linked_list_optimized": {
        "label": "Hash linked list (optimized)",
        "color": "black",
        "linestyle": "-.",
        "marker": "X",
        "markersize": 8,
        "markerfacecolor": "black",
    },
    "hash_linked_list_optimized-X4-H100000": {
        "label": "Hash linked list optimized X4 H100k",
        "color": "black",
        "linestyle": "-.",
        "marker": "X",
        "markersize": 8,
        "markerfacecolor": "black",
    },
    "hash_skip_list": {
        "label": "Hash skip list",
        "color": "blue",
        "linestyle": "--",
        "marker": "^",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "hash_skip_list-X6-H100000": {
        "label": "Hash skip list X6 H100k",
        "color": "blue",
        "linestyle": "--",
        "marker": "^",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "skiplist": {
        "label": "Skip-list",
        "color": "orange",
        "linestyle": "-",
        "marker": "o",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    # "AlwayssortedVector": {
    #     "label": "Always-sorted vector",
    #     "color": "black",
    #     "linestyle": "-.",
    #     "marker": "s",
    #     "markersize": 8,
    #     "markerfacecolor": "none",
    # },
    "AlwayssortedVector-dynamic": {
        "label": "Always-sorted vector dynamic",
        "color": "black",
        "linestyle": "-.",
        "marker": "s",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "AlwayssortedVector-preallocated": {
        "label": "Always-sorted vector prealloc",
        "color": "black",
        "linestyle": "-.",
        "marker": "s",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "UnsortedVector": {
        "label": "Unsorted vector",
        "color": "black",
        "linestyle": "--",
        "marker": "v",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "UnsortedVector-dynamic": {
        "label": "Unsorted vector dynamic",
        "color": "black",
        "linestyle": "--",
        "marker": "v",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "UnsortedVector-preallocated": {
        "label": "Unsorted vector prealloc",
        "color": "black",
        "linestyle": "--",
        "marker": "v",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "hash_linked_list-X6-H100000": {
        "label": "Hash linked list X6 H100k",
        "color": "black",
        "linestyle": "--",
        "marker": "D",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "Vector": {
        "label": "Vector",
        "color": "purple",
        "linestyle": ":",
        "marker": "x",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "Vector-dynamic": {
        "label": "Vector dynamic",
        "color": "purple",
        "linestyle": ":",
        "marker": "x",
        "markersize": 8,
        "markerfacecolor": "none",
    },
    "Vector-preallocated": {
        "label": "Vector prealloc",
        "color": "purple",
        "linestyle": ":",
        "marker": "x",
        "markersize": 8,
        "markerfacecolor": "none",
    },
}
